### ISSUE TITLE
v1.9.7 breaks build with RN0.47

### ISSUE THREAD

**Issue by nihgwu** [yorkie/react-native-wechat#244]
after upgraded to v1.9.7, I can't build ios version, always get build failed , but it works if I downgrade to v1.9.5

**Comment by yorkie** [comment]
Could you please copy the XCode errors here, thanks :)

**Comment by nihgwu** [comment]
the following is only the last part of the log, there are still a bunch of `duplicate symbol` messages
``` bash
duplicate symbol _OBJC_IVAR_$_RCTComponentData._defaultView in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_IVAR_$_RCTComponentData._managerClass in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_IVAR_$_RCTComponentData._shadowPropBlocks in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_IVAR_$_RCTComponentData._viewPropBlocks in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_IVAR_$_RCTComponentData._manager in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_IVAR_$_RCTComponentData._name in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_IVAR_$_RCTComponentData._bridge in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_CLASS_$_RCTComponentData in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_METACLASS_$_RCTComponentData in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTComponentData.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTComponentData.o)
duplicate symbol _OBJC_CLASS_$_RCTNavigatorManager in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTNavigatorManager.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTNavigatorManager.o)
duplicate symbol _OBJC_METACLASS_$_RCTNavigatorManager in:
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libReact.a(RCTNavigatorManager.o)
    /Users/Neo/Github/NeoReader/ios/build/Build/Products/Debug-iphonesimulator/libRCTWeChat.a(RCTNavigatorManager.o)
ld: 756 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **



The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/NeoReader.app/NeoReader normal x86_64
(1 failure)
```

**Comment by vance-liu** [comment]
react-native 0.46.2
same error!

**Comment by yorkie** [comment]
This should get fixed at 1.9.9, specifically at this commit e7d1e75

**Comment by yorkie** [comment]
@nihgwu Does the latest work on NeoReader now?

**Comment by nihgwu** [comment]
yes, tested with the latest version just now, thanks
